function pAgaok(varargin);
% pAgaok( [...] );
% Agilent Ohms 10K
h = timeplot({'T1','T2','T3','T4','T5','T6','T7'}, ...
      'Agilent Ohms 10K', ...
      'Ohms 10K', ...
      {'T1','T2','T3','T4','T5','T6','T7'}, ...
      varargin{:} );
