#ifndef SWSTAT_H_INCLUDED
#define SWSTAT_H_INCLUDED

#define SWS_ACQUIRE 1
#define SWS_IDLE 2
#define SWS_LASER_ACQUIRE 3
#define SWS_CAL1_ACQUIRE 4
#define SWS_DEBUG_ACQUIRE 5
#define SWS_SHUTDOWN 255

#endif

